const areasFlags = [
    { name: "Algerian", code: "dz" },
    { name: "American", code: "us" },
    { name: "Argentinian", code: "ar" },
    { name: "Australian", code: "au" },
    { name: "British", code: "gb" },
    { name: "Canadian", code: "ca" },
    { name: "Chinese", code: "cn" },
    { name: "Croatian", code: "hr" },
    { name: "Dutch", code: "nl" },
    { name: "Egyptian", code: "eg" },
    { name: "Filipino", code: "ph" },
    { name: "French", code: "fr" },
    { name: "Greek", code: "gr" },
    { name: "Indian", code: "in" },
    { name: "Irish", code: "ie" },
    { name: "Italian", code: "it" },
    { name: "Jamaican", code: "jm" },
    { name: "Japanese", code: "jp" },
    { name: "Kenyan", code: "ke" },
    { name: "Malaysian", code: "my" },
    { name: "Mexican", code: "mx" },
    { name: "Moroccan", code: "ma" },
    { name: "Norwegian", code: "no" },
    { name: "Polish", code: "pl" },
    { name: "Portuguese", code: "pt" },
    { name: "Russian", code: "ru" },
    { name: "Saudi Arabian", code: "sa" },
    { name: "Slovakian", code: "sk" },
    { name: "Spanish", code: "es" },
    { name: "Syrian", code: "sy" },
    { name: "Thai", code: "th" },
    { name: "Tunisian", code: "tn" },
    { name: "Turkish", code: "tr" },
    { name: "Ukrainian", code: "ua" },
    { name: "Uruguayan", code: "uy" },
    { name: "Venezuelan", code: "ve" },
    { name: "Vietnamese", code: "vn" },
];

export default areasFlags;